book/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', book_list, name='book_list'),
    path('sing-up/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_user, name='logout'),
    path('<str:slug>/', books_filter, name='books_filter'),
    path('book/create/', CreateBook.as_view(), name='create_book'),
    path('book/<str:slug>/update/', UpdateBook.as_view(), name='update_book'),
    path('book/<str:slug>/delete/', DeleteBook.as_view(), name='delete_book'),
    path('book/<str:slug>/read/', read_book, name='read_book'),
    path('book/<str:slug>/', book_detail, name='book_detail'),
    path('author/<int:pk>/', author_detail, name='author_detail'),
    path('comment/<str:slug>/', AddComment.as_view(), name='add_comment'),
    path('hello/', index)
]

cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', cart_add, name='cart_add'),
    path('remove/<int:book_id>/', cart_remove, name='cart_remove')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('', include('book.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, 11)
]


class CartAddBookForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES)
    update = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST


from book.models import Book
from .helpers import Cart
from .forms import CartAddBookForm


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddBookForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add_or_update(
            book=book,
            quantity=cleaned_data['quantity'],
            update_quantity=cleaned_data['update']
        )
    return redirect('cart:cart_detail')


def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart_detail.html', {})

cart/templates/cart_detail.html
{% extends 'base_book.html' %}
{% block title %} Cart {% endblock %}

{% block content %}
    <h2>Ваша корзина</h2>
        {% if cart %}
            <div class="table-wrapper">
                <table>
                    <thead>
                        <tr style="background-color: #e35f5f;">
                            <th>Картинка</th>
                            <th>Книга</th>
                            <th>Количество</th>
                            <th>Удалить</th>
                            <th>Цена за штуку</th>
                            <th>Цена</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in cart %}
                        {% with book=item.book %}
                            <tr>
                                <td>
                                    <a href="{{ book.get_absolute_url }}">
                                        <img style="height: 120px; width: 70px" class="image fit" src="{{ book.image.url }}">
                                    </a>
                                </td>
                                <td>{{ book.title }}</td>
                                <td>{{ item.quantity }}</td>
                                <td><a class="button small" href="{% url 'cart:cart_remove' book.id %}">Удалить</a></td>
                                <td class="num">{{ item.price }} сом</td>
                                <td class="num">{{ item.total_price }} сом</td>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                    <tr style="margin-top:20px; background-color: #e35f5f; color: #1b1b1b">
                        <td>Общая цена</td>
                        <td colspan="4"></td>
                        <td class="num">{{ cart.get_total_price }} сом</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        {% else %}
            <h3>Ваша корзина пустая</h3>
        {% endif %}
        <p class="text-right">
            <a href="{% url 'book_list' %}" class="button fit">В магазин</a>
            <a style="margin-top: 7px" href="#" class="button fit">Купить</a>
        </p>
{% endblock %}