book/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', book_list, name='book_list'),
    path('sing-up/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_user, name='logout'),
    path('<str:slug>/', books_filter, name='books_filter'),
    path('book/create/', CreateBook.as_view(), name='create_book'),
    path('book/<str:slug>/update/', UpdateBook.as_view(), name='update_book'),
    path('book/<str:slug>/delete/', DeleteBook.as_view(), name='delete_book'),
    path('book/<str:slug>/read/', read_book, name='read_book'),
    path('book/<str:slug>/', book_detail, name='book_detail'),
    path('author/<int:pk>/', author_detail, name='author_detail'),
    path('comment/<str:slug>/', AddComment.as_view(), name='add_comment'),
    path('hello/', index)
]

cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', cart_add, name='cart_add'),
    path('remove/<int:book_id>/', cart_remove, name='cart_remove')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('', include('book.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>{% block title %} Bookshop {% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="{% url 'book_list' %}" class="logo"><strong>Электронные книги</strong></a>
									<ul class="icons">
										<li><a href="https://twitter.com/?lang=ru" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
										<li><a href="https://www.facebook.com/" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
										<li><a href="https://www.instagram.com/" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
										<li><a href="https://ru.linkedin.com/" class="icon brands fa-linkedin"><span class="label">Linkedin</span></a></li>
									</ul>

								</header>
							{% block content %}

							{% endblock %}

						</div>
					</div>

				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form class="d-flex">
										<input id="query" class="form-control me-2" type="search" name="search" placeholder="Поиск" aria-label="Search">
										<button class="button primary icon solid fa-search" type="submit">Поиск</button>
									</form>
								</section>

							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Меню</h2>
									</header>
									<ul>
										<li>
											<a href="{% url 'book_list' %}">Главная Страница</a></li>
										<li>
											<span class="opener">Авторы</span>
											{% if authors %}
												<ul>
													{% for author in authors %}
														<li><a href="{% url 'author_detail' author.id %}">{{ author.name }} {{ author.last_name }}</a></li>
													{% endfor %}
												</ul>
											{% else %}
												<ul>
													<li>Нет результата</li>
												</ul>
											{% endif %}
											{% if request.user.is_authenticated %}
											<li>
												<a href="{% url 'cart:cart_detail' %}">Корзина</a>
											</li>
											<li>
												<a href="{% url 'profile' %}" class="">{{ user.username }}</a>
											</li>
										 	{% else %}
											<li>
												<a href="{% url 'register' %}" >Регистрация</a>
											</li>
											<li>
												<a href="{% url 'login' %}" >Войти</a>
											</li>
											{% endif %}
											<li>
												<span class="opener">Жанры</span>
												{% if genres %}
													<ul>
													{% for genre in genres %}
														<li><a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a></li>
													{% endfor %}
													</ul>
												{% else %}
													<ul>
														<li>Нет результата</li>
													</ul>
												{% endif %}
											</li>
									</ul>
								</nav>

							<!-- Section -->
								<section>
									<header class="major">
										<h2>Контакты</h2>
									</header>
									<ul class="contact">
											<li class="icon solid fa-envelope"><a href="#">eldosyksanov@gmail.com</a></li>
										<li class="icon solid fa-phone">(703)489-202</li>
										<li class="icon solid fa-home">Бишкек</li>
									</ul>
								</section>


						</div>
					</div>

			</div>


			{% if request.user.is_authenticated and request.user.is_staff %}
				<div class="admin-panel align-items-center">
					<a href="admin/" class="btn btn-outline-info">Admin</a>
					{% block admin-panel %}

					{% endblock %}
				</div>
			{% endif %}

		{% if books %}
            <ul class="pagination align-center">
                {% if books.has_previous %}
					<li>
						<a class="page {% if not books.has_previous %} disabled {% endif %}" href="?page=1"><<</a>
					</li>
                {% endif %}
                {% for page in books.paginator.page_range %}
                {% if books.number == page %}
					<li>
						<a class='page active' href="?page={{ page }}">{{ page }}</a>
					</li>
                {% elif page > books.number|add:-3 and page < books.number|add:3 %}
					<li>
						<a class='page' href='?page={{ page }}'>{{ page }}</a>
					</li>
                {% endif %}
                {% endfor %}
                {% if books.end_index %}
					<li>
					   <a class="page" href="?page={{ books.paginator.num_pages }}">>></a>
					</li>
                {% endif %}
            </ul>
        {% endif %}

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>