book/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', book_list, name='book_list'),
    path('sing-up/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_user, name='logout'),
    path('<str:slug>/', books_filter, name='books_filter'),
    path('book/create/', CreateBook.as_view(), name='create_book'),
    path('book/<str:slug>/update/', UpdateBook.as_view(), name='update_book'),
    path('book/<str:slug>/delete/', DeleteBook.as_view(), name='delete_book'),
    path('book/<str:slug>/read/', read_book, name='read_book'),
    path('book/<str:slug>/', book_detail, name='book_detail'),
    path('author/<int:pk>/', author_detail, name='author_detail'),
    path('comment/<str:slug>/', AddComment.as_view(), name='add_comment'),
    path('hello/', index)
]

cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', cart_add, name='cart_add'),
    path('remove/<int:book_id>/', cart_remove, name='cart_remove')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('', include('book.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

book/models.py
from django.db import models
from django.shortcuts import reverse


class Book(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    book = models.TextField(blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='books')
    author = models.ForeignKey('Author', on_delete=models.CASCADE, related_name='books')
    genre = models.ManyToManyField('Genre', related_name='books')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title', )

    def get_absolute_url(self):
        return reverse('book_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('update_book', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('delete_book', kwargs={'slug': self.slug})


class Author(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    image = models.ImageField(blank=True, null=True, upload_to='authors')

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return f'{self.name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('author_detail', kwargs={'pk': self.pk})


class Genre(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )

    def get_absolute_url(self):
        return reverse('books_filter', kwargs={'slug': self.slug})


class Comment(models.Model):
    title = models.TextField()
    book = models.ForeignKey('Book', on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

book/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import *


class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'slug', 'price', 'description', 'image', 'author', 'genre']

    def clean(self):
        slug = self.cleaned_data.get('title').lower().replace(' ', '-')
        if Book.objects.filter(slug=slug).exists():
            raise forms.ValidationError('Book with such title already exists!')
        return self.cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('title', )


class RegistrationForm(UserCreationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        template_name = 'book/register.html'
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        template_name = 'book/login.html'
        fields = ['username', 'password1']

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout, login
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin

from .utils import RegisterOrLoginMixin
from .models import *
from .forms import *


def book_list(request):
    books = Book.objects.all()
    genres = Genre.objects.all()
    authors = Author.objects.all()

    search = request.GET.get('search', '')
    if search:
        books = Book.objects.filter(title__icontains=search)

    paginator = Paginator(books, settings.PAGINATOR_NUM)
    page_number = request.GET.get('page', 1)
    books = paginator.get_page(page_number)

    context = {
        'books': books,
        'genres': genres,
        'authors': authors,
    }
    return render(request, 'book/book_list.html', context)


def books_filter(request, slug):
    books = Book.objects.filter(genre__slug=slug)
    return render(request, 'book/books_filter.html', {'books': books})


def book_detail(request, slug):
    book = get_object_or_404(Book, slug__iexact=slug)
    return render(request, 'book/book_detail.html', {'book': book, 'detail': True})


def read_book(request, slug):
    book = get_object_or_404(Book, slug__iexact=slug)
    return render(request, 'book/read_book.html', {'book': book})


def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    author_books = author.books.all()
    context = {
        'author': author,
        'author_books': author_books,
    }
    return render(request, 'book/author_detail.html', context)


class CreateBook(LoginRequiredMixin, View):
    raise_exception = True

    def get(self, request):
        form = CreateBookForm()
        return render(request, 'book/create_book.html', {'form': form})

    def post(self, request):
        bound_form = CreateBookForm(request.POST, request.FILES)
        if bound_form.is_valid():
            new_book = bound_form.save()
            return redirect(new_book.get_absolute_url())
        return render(request, 'book/create_book.html', {'form': bound_form})


class UpdateBook(LoginRequiredMixin, View):
    raise_exception = True

    def get(self, request, slug):
        book = get_object_or_404(Book, slug__iexact=slug)
        bound_form = CreateBookForm(instance=book)
        return render(request, 'book/book_update.html', {'form': bound_form, 'book': book})

    def post(self, request, slug):
        book = get_object_or_404(Book, slug__iexact=slug)
        bound_form = CreateBookForm(request.POST, instance=book)
        if bound_form.is_valid():
            update_book = bound_form.save()
            return redirect(update_book.get_absolute_url())
        return render(request, 'book/book_detail.html', {'form': bound_form, 'book': book})


class DeleteBook(LoginRequiredMixin, View):
    raise_exception = True

    def get(self, request, slug):
        book = get_object_or_404(Book, slug__iexact=slug)
        return render(request, 'book/delete_book.html', {'book': book})

    def post(self, request, slug):
        book = get_object_or_404(Book, slug__iexact=slug)
        book.delete()
        return redirect(reverse('book_list'))


class CommentDetail(View):
    def get(self, request, slug):
        book = get_object_or_404(Book, slug)
        return render(request, 'book/book_detail.html', {'book': book})


class AddComment(View):
    def post(self, request, slug):
        comment_form = CommentForm(request.POST)
        book = Book.objects.get(slug=slug)
        if comment_form.is_valid():
            form = comment_form.save(commit=False)
            form.book = book
            form.save()
        return redirect('/')


class Register(RegisterOrLoginMixin, CreateView):
    form_class = RegistrationForm
    template_name = 'book/register.html'
    register_or_login_form = 'registration_form'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('book_list')


class Login(RegisterOrLoginMixin, LoginView):
    form_class = LoginForm
    template_name = 'book/login.html'
    register_or_login_form = 'login_form'


def logout_user(request):
    logout(request)
    return redirect('book_list')


def profile(request):
    return render(request, 'book/profile.html')


def index(request):
    return render(request, 'book/index.html')

book/templates/book/author_detail.html
{%  extends 'base_book.html' %}
{% load static %}
{% block title %}
    Author Detail
{% endblock %}

{% block content %}
<section id="banner">
    <div class="content">
        <header>
            <h1>{{ author.name }} {{ author.last_name }}</h1>
            <p>Год рождения: {{ author.date_of_birth }}</p>
        </header>
        <h4>Произведения: </h4>
        {% for book in author_books %}
            <p><a href="{{ book.get_absolute_url }}">{{ book }}</a></p>
        {% endfor %}
    </div>
    <div class="mini-posts">
        {% if author.image %}
        <article>
            <a href="#" class="image"><img src="{{ author.image.url }}" alt=""  /></a>
        </article>
        {% else %}
        <article>
            <a href="#" class="image"><img src="{% static 'images/default_user.jpg' %}" alt="" /></a>
        </article>
        {% endif %}
    </div>
</section>
{% endblock %}

book/templates/book/book_detail.html
{%  extends 'base_book.html' %}
{% load static %}
{% block title %}
    Book Detail
{% endblock %}

{% block content %}
<!-- Content -->
	<section>
		<header class="main">
			<h2>{{ book.title }}</h2>
		</header>
		{% if book.image %}
			<span class="image main"><img src="{{ book.image.url }}" alt="" style="width: 400px; height: 550px" /></span>
		{% else %}
			<span class="image main"><img src="{% static 'images/default.jpg' %}" alt="" style="width: 400px; height: 550px" /></span>
		{% endif %}

		{% if request.user.is_authenticated %}
			<form action="{% url 'cart:cart_add' book.id %}" class="cart d-flex justify-content-between total font-weight-bold mt-4" method="post" enctype='multipart/form-data'>
				{% csrf_token %}
					<div class="quantity" name="demo-category">
					  <input type="number" step="1" max="10" min="1"  name="quantity" value="1" title="Qty" class="input-text qty text" size="4" />
					</div>
				<input type="hidden" name="add-to-cart" value="4015" />
				<button type="submit" class="button primary fit small">Добавить в корзину</button>
		  	</form>

			<div class="d-flex justify-content-between total font-weight-bold mt-4">
				<a href="{% url 'read_book' book.slug %}" class="button primary fit small">Читать</a>
			</div>
		{% endif %}

		<hr class="major" />
		<div class="content">
			<header>
				<h2>Описание: </h2>
				<p>{{ book.description }}</p>
			</header>
    	</div>
		<h3>Комментарии ({{ book.comments.all|length }})</h3>

		{% if book.comments %}
			{% for comment in book.comments.all %}

				<div class="box">
					<h6 class="headers">{{comment.created_at}}</h6>
					<div class="box">
						{{comment.title}}

						{% if request.user.is_authenticated %}
						<div>
							<a href="#" class="" style="margin-right: 5px">Изменить</a>
							<a href="#" class="">Удалить</a>
						</div>
						{% endif %}
					</div>
				</div>

			{% endfor %}
		{% endif %}

		<form action="{% url 'add_comment' book.slug %}" method="post" id="commentform" class="comment">
			{% csrf_token %}
			<div class="col-12" style="margin-top: 10px">
				<textarea name="comment" id="comment" placeholder="Введите комментарий" rows="6" aria-required="true"></textarea>
				<input style="margin-top: 10px" type="submit" value="Отправить" class="primary" />
			</div>
		</form>

	</section>
{% endblock %}

book/templates/book/book_list.html
{%  extends 'base_book.html' %}
{% load static %}
{% block title %}
    Book List
{% endblock %}

{% block content %}
<!-- Section -->
    <section>
        <header class="major">
            <h2>Книги</h2>
        </header>
        <div class="posts">
            {% for book in books %}
            <article>
                {% if book.image %}
                    <a href="{{ book.get_absolute_url }}" class="image"><img src="{{ book.image.url }}" alt="" style="width: 350px; height: 500px" /></a>
                {% else %}
                    <a href="{{ book.get_absolute_url }}" class="image"><img src="{% static 'images/default.jpg' %}" alt="" style="width: 350px; height: 500px" /></a>
                {% endif %}
                <h3>{{ book.title }}</h3>
                <p>{{ book.price }} сом</p>
                <ul class="actions">
                    <li><a href="{{ book.get_absolute_url }}" class="button primary">Подробнее</a></li>
                </ul>
            </article>
            {% endfor %}
        </div>

    </section>
{% endblock %}

book/templates/book/book_update.html
{% extends 'base_book.html' %}
{% block title %} Book Update {% endblock %}

{% block content %}
    <form action="{{ book.get_update_url }}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {{ form.errors }}
                </div>
            {% endif %}
        {{ form.as_p }}
        <button type="submit" class="button">Обновить</button>
    </form>
{% endblock %}

book/templates/book/books_filter.html
{%  extends 'base_book.html' %}
{% load static %}
{% block title %}
    Filter Book
{% endblock %}

{% block content %}

<!-- Section -->
<section>
    <header class="major">
        <h2>Books</h2>
    </header>
    <div class="posts">
        {% for book in books %}
        <article>
            {% if book.image %}
                <a href="#" class="image"><img src="{{ book.image.url }}" alt="" style="width: 350px; height: 500px" /></a>
            {% else %}
                <a href="#" class="image"><img src="{% static 'images/default.jpg' %}" alt="" style="width: 350px; height: 500px" /></a>
            {% endif %}
            <h3>{{ book.title }}</h3>
            <p>{{ book.price }}</p>
            <ul class="actions">
                <li><a href="{{ book.get_absolute_url }}" class="button primary">Подробнее</a></li>
            </ul>
        </article>
        {% endfor %}
    </div>

    {% if books %}
            <ul class="pagination align-center">
                {% if books.has_previous %}
					<li>
						<a class="page {% if not books.has_previous %} disabled {% endif %}" href="?page=1"><<</a>
					</li>
                {% endif %}
                {% for page in books.paginator.page_range %}
                {% if books.number == page %}
					<li>
						<a class='page active' href="?page={{ page }}">{{ page }}</a>
					</li>
                {% elif page > books.number|add:-3 and page < books.number|add:3 %}
					<li>
						<a class='page' href='?page={{ page }}'>{{ page }}</a>
					</li>
                {% endif %}
                {% endfor %}
                {% if books.end_index %}
					<li>
					   <a class="page" href="?page={{ books.paginator.num_pages }}">>></a>
					</li>
                {% endif %}
            </ul>
        {% endif %}
</section>
{% endblock %}

book/templates/book/create_book.html
{% extends 'base_book.html' %}
{% block title %} Create Book {% endblock %}

{% block content %}
    <form action="{% url 'create_book' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {{ form.errors }}
                </div>
            {% endif %}
        {{ form.as_p }}
        <button type="submit" class="button">Добавить</button>
    </form>
{% endblock %}

book/templates/book/delete_book.html
{% extends 'base_book.html' %}
{% block title %} Book Delete {% endblock %}

{% block content %}
    <form action="{{ book.get_delete_url }}" method="post">
        {% csrf_token %}
        <h3 style="margin-top: 70px">Вы уверены что хотите удалить книгу "{{ book.title }}"?</h3>
        <button type="submit" class="button"><a href="{{ book.get_absolute_url }}">Отмена</a></button>

        <button type="submit" class="button primary">Удалить</button>
    </form>
{% endblock %}

book/templates/book/index.html
<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Generic - Editorial by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="index.html" class="logo"><strong>Editorial</strong> by HTML5 UP</a>
									<ul class="icons">
										<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
										<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
										<li><a href="#" class="icon brands fa-snapchat-ghost"><span class="label">Snapchat</span></a></li>
										<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
										<li><a href="#" class="icon brands fa-medium-m"><span class="label">Medium</span></a></li>
									</ul>
								</header>

							<!-- Content -->
								<section>
									<header class="main">
										<h1>Generic</h1>
									</header>

									<span class="image main"><img src="images/pic11.jpg" alt="" /></span>

									<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit.</p>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel sed vehicula.</p>
									<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>

									<hr class="major" />

									<h2>Interdum sed dapibus</h2>
									<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit.</p>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel sed vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>

									<hr class="major" />

									<h2>Magna etiam veroeros</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel sed vehicula.</p>
									<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>

									<hr class="major" />

									<h2>Lorem aliquam bibendum</h2>
									<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit.</p>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel sed vehicula.</p>

								</section>

						</div>
					</div>

				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form method="post" action="#">
										<input type="text" name="query" id="query" placeholder="Search" />
									</form>
								</section>

							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="index.html">Homepage</a></li>
										<li><a href="generic.html">Generic</a></li>
										<li><a href="elements.html">Elements</a></li>
										<li>
											<span class="opener">Submenu</span>
											<ul>
												<li><a href="#">Lorem Dolor</a></li>
												<li><a href="#">Ipsum Adipiscing</a></li>
												<li><a href="#">Tempus Magna</a></li>
												<li><a href="#">Feugiat Veroeros</a></li>
											</ul>
										</li>
										<li><a href="#">Etiam Dolore</a></li>
										<li><a href="#">Adipiscing</a></li>
										<li>
											<span class="opener">Another Submenu</span>
											<ul>
												<li><a href="#">Lorem Dolor</a></li>
												<li><a href="#">Ipsum Adipiscing</a></li>
												<li><a href="#">Tempus Magna</a></li>
												<li><a href="#">Feugiat Veroeros</a></li>
											</ul>
										</li>
										<li><a href="#">Maximus Erat</a></li>
										<li><a href="#">Sapien Mauris</a></li>
										<li><a href="#">Amet Lacinia</a></li>
									</ul>
								</nav>

							<!-- Section -->
								<section>
									<header class="major">
										<h2>Ante interdum</h2>
									</header>
									<div class="mini-posts">
										<article>
											<a href="#" class="image"><img src="images/pic07.jpg" alt="" /></a>
											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
										</article>
										<article>
											<a href="#" class="image"><img src="images/pic08.jpg" alt="" /></a>
											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
										</article>
										<article>
											<a href="#" class="image"><img src="images/pic09.jpg" alt="" /></a>
											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
										</article>
									</div>
									<ul class="actions">
										<li><a href="#" class="button">More</a></li>
									</ul>
								</section>

							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
									<ul class="contact">
										<li class="icon solid fa-envelope"><a href="#">information@untitled.tld</a></li>
										<li class="icon solid fa-phone">(000) 000-0000</li>
										<li class="icon solid fa-home">1234 Somewhere Road #8254<br />
										Nashville, TN 00000-0000</li>
									</ul>
								</section>

							<!-- Footer -->
								<footer id="footer">
									<p class="copyright">&copy; Untitled. All rights reserved. Demo Images: <a href="https://unsplash.com">Unsplash</a>. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
								</footer>

						</div>
					</div>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>